import React, { useState } from "react";
import {
  Box,
  Button,
  Card,
  CardContent,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  IconButton,
  InputAdornment,
  TextField,
  Typography,
} from "@mui/material";
import LockOutlinedIcon from "@mui/icons-material/LockOutlined";
import { Visibility, VisibilityOff } from "@mui/icons-material";
import { useNavigate } from "react-router-dom";
import { cognitoChangePassword } from "../../utils/cognitoAuth";

// Providers whose password lives in Cognito and is owned by the user.
// "cognito" = native email/password signup, so the current password is known
// and can be changed in place. Anything else is federated: the Cognito
// password was generated by the backend during bootstrap and is unknown to
// the user, so it has to be established through the reset (OTP) flow.
const NATIVE_PROVIDER = "cognito";

// IMAA WordPress OAuth users are excluded from backend password enablement
// (COGNITO_SKIP_LOCAL_PASSWORD_PROVIDERS), so neither changing nor resetting
// a password here would work for them — WordPress owns their credentials.
const EXTERNALLY_MANAGED_PROVIDERS = ["imaawordpressoauth"];

function ChangePasswordDialog({ open, onClose }) {
  const [currentPassword, setCurrentPassword] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(false);
  const [showCurrentPassword, setShowCurrentPassword] = useState(false);
  const [showNewPassword, setShowNewPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);

  const visibilityAdornment = (shown, toggle, label) => ({
    endAdornment: (
      <InputAdornment position="end">
        <IconButton onClick={toggle} edge="end" aria-label={label} tabIndex={-1}>
          {shown ? <VisibilityOff fontSize="small" /> : <Visibility fontSize="small" />}
        </IconButton>
      </InputAdornment>
    ),
  });

  const submit = async () => {
    setMessage("");
    if (newPassword !== confirmPassword) {
      setMessage("New password and confirm password do not match.");
      return;
    }

    const username = localStorage.getItem("last_cognito_username") || localStorage.getItem("last_login_email");
    if (!username) {
      setMessage("Unable to identify logged-in user.");
      return;
    }

    try {
      setLoading(true);
      await cognitoChangePassword({ usernameOrEmail: username, currentPassword, newPassword });
      setMessage("Password changed successfully.");
      setTimeout(() => onClose(), 1000);
    } catch (error) {
      setMessage(error?.message || "Failed to change password.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm">
      <DialogTitle>Change Password</DialogTitle>
      <DialogContent>
        <TextField
          margin="normal"
          fullWidth
          type={showCurrentPassword ? "text" : "password"}
          label="Current Password"
          value={currentPassword}
          onChange={(e) => setCurrentPassword(e.target.value)}
          InputProps={visibilityAdornment(
            showCurrentPassword,
            () => setShowCurrentPassword((v) => !v),
            "toggle current password visibility"
          )}
        />
        <TextField
          margin="normal"
          fullWidth
          type={showNewPassword ? "text" : "password"}
          label="New Password"
          value={newPassword}
          onChange={(e) => setNewPassword(e.target.value)}
          InputProps={visibilityAdornment(
            showNewPassword,
            () => setShowNewPassword((v) => !v),
            "toggle new password visibility"
          )}
        />
        <TextField
          margin="normal"
          fullWidth
          type={showConfirmPassword ? "text" : "password"}
          label="Confirm New Password"
          value={confirmPassword}
          onChange={(e) => setConfirmPassword(e.target.value)}
          InputProps={visibilityAdornment(
            showConfirmPassword,
            () => setShowConfirmPassword((v) => !v),
            "toggle confirm password visibility"
          )}
        />
        {message && <Typography sx={{ mt: 2 }} color="text.secondary">{message}</Typography>}
      </DialogContent>
      <DialogActions>
        <Button onClick={onClose}>Cancel</Button>
        <Button variant="contained" onClick={submit} disabled={loading}>Change Password</Button>
      </DialogActions>
    </Dialog>
  );
}

export default function SecurityCard({ provider = "", email = "" }) {
  const [open, setOpen] = useState(false);
  const navigate = useNavigate();

  const normalizedProvider = String(provider || "").trim().toLowerCase();
  // Default to the native flow when provider is unknown (missing/older API
  // response) so existing email/password users keep today's behaviour.
  const isFederated = Boolean(normalizedProvider) && normalizedProvider !== NATIVE_PROVIDER;
  const isExternallyManaged = EXTERNALLY_MANAGED_PROVIDERS.includes(normalizedProvider);

  const providerLabel = normalizedProvider === "google" ? "Google" : "an external provider";

  const header = (
    <>
      <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
        <LockOutlinedIcon fontSize="small" />
        <Typography variant="h6">Security</Typography>
      </Box>
    </>
  );

  // Password is owned by WordPress — neither change nor reset works here.
  if (isExternallyManaged) {
    return (
      <Card>
        <CardContent>
          {header}
          <Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>
            Your password is managed by your IMAA website account. Please update
            it there.
          </Typography>
        </CardContent>
      </Card>
    );
  }

  // Federated (e.g. Google): the Cognito password was generated during login
  // bootstrap and is unknown to the user, so send them to the existing reset
  // flow instead of asking for a current password they cannot know.
  if (isFederated) {
    return (
      <Card>
        <CardContent>
          {header}
          <Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>
            You signed in using {providerLabel}.
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>
            To create or update your password, use password reset. You can then
            also sign in with your email and password.
          </Typography>
          <Button
            sx={{ mt: 2 }}
            variant="contained"
            size="small"
            onClick={() => navigate("/account/set-password", { state: { email } })}
          >
            Set Password
          </Button>
        </CardContent>
      </Card>
    );
  }

  return (
    <>
      <Card>
        <CardContent>
          {header}
          <Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>
            Manage your account password securely.
          </Typography>
          <Button sx={{ mt: 2 }} variant="contained" size="small" onClick={() => setOpen(true)}>
            Change Password
          </Button>
        </CardContent>
      </Card>
      <ChangePasswordDialog open={open} onClose={() => setOpen(false)} />
    </>
  );
}
